//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bitbird.Core.Utils.AzureReporting.Net.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bitbird.Core.Utils.AzureReporting.Net.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to high.
        /// </summary>
        public static string Bitbird_Core_Api_AzureReporting_Net_Models_Priority_High {
            get {
                return ResourceManager.GetString("Bitbird_Core_Api_AzureReporting_Net_Models_Priority_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to medium.
        /// </summary>
        public static string Bitbird_Core_Api_AzureReporting_Net_Models_Priority_Medium {
            get {
                return ResourceManager.GetString("Bitbird_Core_Api_AzureReporting_Net_Models_Priority_Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mustfix.
        /// </summary>
        public static string Bitbird_Core_Api_AzureReporting_Net_Models_Priority_MustFix {
            get {
                return ResourceManager.GetString("Bitbird_Core_Api_AzureReporting_Net_Models_Priority_MustFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unimportant.
        /// </summary>
        public static string Bitbird_Core_Api_AzureReporting_Net_Models_Priority_Unimportant {
            get {
                return ResourceManager.GetString("Bitbird_Core_Api_AzureReporting_Net_Models_Priority_Unimportant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to critical.
        /// </summary>
        public static string Bitbird_Core_Api_AzureReporting_Net_Models_Severity_Critical {
            get {
                return ResourceManager.GetString("Bitbird_Core_Api_AzureReporting_Net_Models_Severity_Critical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to high.
        /// </summary>
        public static string Bitbird_Core_Api_AzureReporting_Net_Models_Severity_High {
            get {
                return ResourceManager.GetString("Bitbird_Core_Api_AzureReporting_Net_Models_Severity_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to low.
        /// </summary>
        public static string Bitbird_Core_Api_AzureReporting_Net_Models_Severity_Low {
            get {
                return ResourceManager.GetString("Bitbird_Core_Api_AzureReporting_Net_Models_Severity_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to medium.
        /// </summary>
        public static string Bitbird_Core_Api_AzureReporting_Net_Models_Severity_Medium {
            get {
                return ResourceManager.GetString("Bitbird_Core_Api_AzureReporting_Net_Models_Severity_Medium", resourceCulture);
            }
        }
    }
}
